services:
  skins-app:
    build: .
    container_name: skins-web-modern
    restart: always
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
      - ./vhost.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - DB_HOST=127.0.0.1
      - DB_NAME=database_name
      - DB_USER=database_user
      - DB_PASS=database_password
